name: Scheduled FastAPI Scraper

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at midnight UTC
  workflow_dispatch:      # Manual trigger for first run

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Try to download accounts.db
        id: download
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: twscrape-db
          path: .

      - name: Seed accounts.db from secret if missing
        if: steps.download.outcome == 'failure'
        run: |
          echo "${{ secrets.ENCODED_DB }}" | base64 --decode > accounts.db

      - name: Run your app
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Upload updated accounts.db
        uses: actions/upload-artifact@v3
        with:
          name: twscrape-db
          path: accounts.db
